name = "dyndns"
main = "src/index.ts"
compatibility_date = "2023-10-10"

# If you want to use a default route on workers.dev, set this to true
workers_dev = false
# If you want to use a custom domain adapt the example domain or else remove or comment out the routes section
routes = [
	{ pattern = "dyndns.example.com", custom_domain = true }
]

[vars]
# USERNAME="username"
# PASSWORD="password"
# CF_API_TOKEN="token"
# DNS_ZONE_ID="zone_id"
